### ISSUE TITLE
Make table sortable

### ISSUE THREAD

**Issue by naturallymitchell** [alilleybrinker/langs-in-rust#20]
for example: by # of stars, # of contributors, date created, has batteries included.

https://stackoverflow.com/questions/42843288/is-there-any-way-to-make-markdown-tables-sortable

https://github.com/tofsjonas/sortable

https://github.com/HubSpot/sortable

**Comment by alilleybrinker** [comment]
All of the resources you linked describe how to make a table sortable in specific situations. The first link is for users to make tables sortable for their own use with user scripts. The second and third links are for developers to make tables they're building sortable with the inclusion of CSS and JavaScript. Unfortunately none of these options are usable in the context of a GitHub-flavored Markdown table rendered in a repository's README. At some point this repo could have a GitHub Pages site and that site could have a sortable table, but for now making the current table sortable isn't doable.
