### ISSUE TITLE
Automate updating the table.

### ISSUE THREAD

**Issue by alilleybrinker** [alilleybrinker/langs-in-rust#25]
There are enough languages in the list now that it's pretty tedious to go and update everything. A better solution would be to have all the languages input in a data file which can then be read by a script which does the following:

- For each repository, grabs the stars numbers, checks whether it's been updated in the last year, and pulls the description.
- Updates the `README.md` with this data, sorted on activity, number of stars, name, in that order.

**Comment by NoName-hack-e** [comment]
do you want me to help you? m8

**Comment by NoName-hack-e** [comment]
hi i can hellp you to make one
@alilleybrinker

**Comment by alilleybrinker** [comment]
Do you have a draft design in mind?

**Comment by NoName-hack-e** [comment]
umm maybe a python progrm that check github api every time is exeute(sorry for bad englis im from afg)

**Comment by alilleybrinker** [comment]
This was resolved by #35.
