### ISSUE TITLE
frawk: fast AWK like language 

### ISSUE THREAD

**Issue by ghuls** [alilleybrinker/langs-in-rust#26]
> 
> frawk is a small programming language for writing short programs processing textual data. To a first approximation, it is an implementation of the AWK language; many common Awk programs produce equivalent output when passed to frawk. You might be interested in frawk if you want your scripts to handle escaped CSV/TSV like standard Awk fields, or if you want your scripts to execute faster.
> 
> The info subdirectory has more in-depth information on frawk:
> 
>     Overview: what frawk is all about, how it differs from Awk.
>     Types: A quick gloss on frawk's approach to types and type inference.
>     Parallelism: An overview of frawk's parallelism support.
>     Benchmarks: A sense of the relative performance of frawk and other tools when processing large CSV or TSV files.
>     Builtin Functions Reference: A list of builtin functions implemented by frawk, including some that are new when compared with Awk.

https://github.com/ezrosent/frawk

**Comment by alilleybrinker** [comment]
Closed by https://github.com/alilleybrinker/langs-in-rust/pull/29
