### ISSUE TITLE
Consider adding `swc` or replacing `Parcel` with `swc`?

### ISSUE THREAD

**Issue by chuanqisun** [alilleybrinker/langs-in-rust#42]
- `swc` is the underlying transpiler for `Parcel`
- Reference: https://swc.rs/
- The existing caveat can be removed: 
  > Parcel is a large project of which the JavaScript transformer (written in Rust) is a small part. The "stars" number here reflects the whole project, which is broader than a programming language project.

**Comment by alilleybrinker** [comment]
I'd prefer to add, rather than replace. Parcel is still worth linking to. Care to open a PR?
