### ISSUE TITLE
Add jakt

### ISSUE THREAD

**Issue by joshnatis** [alilleybrinker/langs-in-rust#47]
https://github.com/SerenityOS/jakt

**Comment by alilleybrinker** [comment]
Added in #48.

**Comment by auronandace** [comment]
While Jakt is certainly still active they have completely replaced the rust-based compiler with a self-hosted one. Not sure if this means you want to remove it from the list or maybe add a sort of historical note.

**Comment by alilleybrinker** [comment]
Alright, I'll reopen this then so I don't forget to add the note. Thanks!

**Comment by alerque** [comment]
Both #96 and its replacement #107 just remove this as it is not a language written in Rust any more, but if you want a historical note that is fine, feel free to tweak my PR or amend later or request it there or whatever.

**Comment by alilleybrinker** [comment]
Removal is fine. Thanks!
