### ISSUE TITLE
Add SSP1601 assembler

### ISSUE THREAD

**Issue by jdesiloniz** [alilleybrinker/langs-in-rust#68]
https://github.com/jdesiloniz/svpdev/tree/master/tools/ssp16asm

This repository holds an assembler for the SSP1601 DSP found on the SVP chip (powering the Virtua Racing game for the Mega Drive/Genesis gaming console). It's the only available assembler for this DSP at this moment.

**Comment by alilleybrinker** [comment]
Added!
