### ISSUE TITLE
Some more langs

### ISSUE THREAD

**Issue by aDotInTheVoid** [alilleybrinker/langs-in-rust#7]
I'm not sure what you what the criteria for conculsion is

https://github.com/BlazifyOrg/blazescript
https://github.com/facebookexperimental/starlark-rust
https://github.com/Kixiron/crunch-lang
https://github.com/arzg/eldiro
https://github.com/Starlight-JS/Starlight
https://github.com/vmware/differential-datalog
https://github.com/boa-dev/boa
https://github.com/munificent/craftinginterpreters/wiki/Lox-implementations#rust
https://github.com/aDotInTheVoid/skate/ (disclaimer: this is mine)

**Comment by yusdacra** [comment]
I would also like to suggest https://github.com/tweag/nickel

**Comment by fennecdjay** [comment]
Actually I know quite a few people making languages in rust, some of them are already usable, shall I tell them this repo exists?

**Comment by alilleybrinker** [comment]
Thanks for all these additions! I'll find some time to get them added.

**Comment by alilleybrinker** [comment]
Oh, and the criteria for inclusion (which I ought to write out in the README) is just "is this a programming language?" The point here is to collect works in this area so people can use them as reference for implementing their own, or if they're just interested in exploring this space.

**Comment by fennecdjay** [comment]
Oh, the point is "is this a programming language in rust?" maybe, otherwise I'd shamelessly plug mine tbh :)

---
I'm leaving the link for the curions
https://github.com/Gwion/Gwion

**Comment by alilleybrinker** [comment]
Yes, "in Rust" as well. Thanks for the additional link!

**Comment by fennecdjay** [comment]
OK so my friends now know about this repo, I wouldn't be too surprised if the list grows fast in the next hours/days!

Thanks for the idea

**Comment by alilleybrinker** [comment]
@yusdacra, added Nickel.

**Comment by alilleybrinker** [comment]
Gonna close this and open a new issue for the Lox implementations.
