### ISSUE TITLE
Set Astro to inactive

### ISSUE THREAD

**Issue by Erithax** [alilleybrinker/langs-in-rust#71]
The last commit to the [repo](https://github.com/astrolang/astro) was in 2019 and their website has been unreachable since 2021 (mentioned in an issue).

**Comment by alilleybrinker** [comment]
Good catch! This actually led me to discover the prior logic for checking activity from the GitHub API was wrong, and it's not fixed. This led to 29 languages now being marked as inactive which previously showed as active:

1. Astro
1. Blazescript
1. CalcuLaTeX
1. Darksecond/lox
1. Eldiro
1. Iron
1. Jazz
1. Ketos
1. Minitt
1. Monkey-Rust
1. Passerine
1. Pikelet
1. Rust-Lisp
1. Rust-Prolog
1. Sphinx
1. Starlight
1. Voile
1. Wain
1. 🌌
1. atto
1. cat-lox
1. lox-rs
1. loxr
1. loxrs
1. radogost/rlox
1. rctcwyvrn/rlox
1. rodaine/rlox
1. roxt
1. rulox

**Comment by Erithax** [comment]
Aha, I was going through and thinking that a lot seemed to be mislabeled. Glad I started with reporting just one!
