### ISSUE TITLE
Add ante

### ISSUE THREAD

**Issue by fennecdjay** [alilleybrinker/langs-in-rust#9]
Ante is a low-level mostly functional programming language targetted at gamedev but is still applicable for most domains.

https://github.com/jfecher/ante

As I said, I know a bunch of other langs in rust, but I think you don't wanna miss this one.

**Comment by alilleybrinker** [comment]
Thanks! I'll add it as soon as I can 😄

**Comment by alilleybrinker** [comment]
Done!
